import pandas as pd
import numpy as np
import re
from data_processor import calculate_top_10_kpis, get_top_authors_leaderboard


def query_ai_copilot(df, prompt):
    """
    Fast built-in Python/Pandas natural language research assistant for BAMU Scopus Data.
    Analyzes queries instantly and generates rich, structured Markdown insights with zero external API dependencies.
    """
    if df is None or df.empty:
        return "⚠️ **No publication data available to analyze.** Please adjust dashboard filters or load data."

    prompt_lower = prompt.lower().strip()
    total_pubs = len(df)
    total_cites = int(df['citations'].sum()) if 'citations' in df.columns else 0
    avg_cpp = round(total_cites / max(1, total_pubs), 2)

    # 1. Executive Dossier / Overview Intent
    if any(k in prompt_lower for k in ["executive", "dossier", "overview", "summary", "kpi", "report"]):
        kpis = calculate_top_10_kpis(df)
        top_depts = df['department'].value_counts().head(3)
        top_authors_df = get_top_authors_leaderboard(df, top_n=3)
        
        dept_str = ", ".join([f"**{d}** ({c} papers)" for d, c in top_depts.items()])
        author_str = ", ".join([f"**{r['author']}** (h-{r['h_index']})" for _, r in top_authors_df.iterrows()]) if not top_authors_df.empty else "N/A"

        res = f"""### 📊 BAMU Executive Scopus Intelligence Dossier

- 📜 **Total Indexed Output:** `{kpis['total_output']:,}` Scopus publications
- 📈 **Total Citations Earned:** `{kpis['total_citations']:,}` citations (Avg. `{kpis['citations_per_paper']}` CPP)
- ⭐ **Q1 High-Impact Share:** `{kpis['q1_count']:,}` papers (`{kpis['q1_percentage']}%`)
- 🌐 **Global Collaboration Rate:** `{kpis['international_collab_pct']}%`
- 🏭 **Industry R&D Share:** `{kpis['industry_collab_pct']}%`
- ⚡ **Indexing Velocity (Last 30 Days):** `+{kpis['last_30_days_velocity']}` papers

#### 🏛️ Top Contributing Departments:
{dept_str}

#### 🏆 Top Performing Faculty Spotlight:
{author_str}

---
*Generated by BAMU Scopus AI Copilot (Built-in Pandas Analytics Engine)*
"""
        return res

    # 2. Department Rankings Intent
    elif any(k in prompt_lower for k in ["dept", "department", "ranking", "comparison", "branch"]):
        dept_summary = df.groupby('department').agg(
            Papers=('scopus_id', 'count'),
            Citations=('citations', 'sum'),
            Avg_CPP=('citations', 'mean'),
            Q1_Papers=('quartile', lambda x: (x == 'Q1').sum())
        ).reset_index()

        dept_summary['Avg_CPP'] = dept_summary['Avg_CPP'].round(2)
        dept_summary = dept_summary.sort_values(by=['Papers', 'Citations'], ascending=False).head(10)

        table_rows = ""
        for idx, row in dept_summary.iterrows():
            table_rows += f"| **{row['department']}** | {row['Papers']} | {row['Citations']:,} | {row['Avg_CPP']} | {row['Q1_Papers']} |\n"

        res = f"""### 🏛️ Academic Department Research Ranking

| Department | Papers | Citations | Avg CPP | Q1 Papers |
| :--- | :---: | :---: | :---: | :---: |
{table_rows}
> 💡 **Key Takeaway:** **{dept_summary.iloc[0]['department']}** leads the university in total volume with **{dept_summary.iloc[0]['Papers']}** indexed publications.
"""
        return res

    # 3. Q1 Quality Analysis Intent
    elif any(k in prompt_lower for k in ["q1", "quality", "quartile", "impact factor", "prestigious"]):
        q_counts = df['quartile'].value_counts()
        q1_count = q_counts.get('Q1', 0)
        q1_pct = round((q1_count / max(1, total_pubs)) * 100, 1)

        q1_df = df[df['quartile'] == 'Q1'].sort_values('citations', ascending=False)
        top_journals = q1_df['journal'].value_counts().head(5)
        top_papers = q1_df.head(3)

        journal_list = "\n".join([f"- **{j}** ({c} Q1 papers)" for j, c in top_journals.items()])
        
        paper_list = ""
        for idx, r in top_papers.iterrows():
            paper_list += f"1. **{r['title']}**\n   - *Journal:* {r['journal']} ({r['year']}) | *Citations:* {r['citations']:,} | *DOI:* `{r['doi']}`\n"

        res = f"""### 🏆 Journal Quality & Q1 Benchmark Analysis

- 🌟 **Q1 Journal Publications:** `{q1_count:,}` out of `{total_pubs:,}` papers (**{q1_pct}%** of university portfolio)
- 📊 **Quartile Distribution:** Q1: `{q_counts.get('Q1', 0)}` | Q2: `{q_counts.get('Q2', 0)}` | Q3: `{q_counts.get('Q3', 0)}` | Q4: `{q_counts.get('Q4', 0)}`

#### 📰 Preferred Q1 Journals for BAMU Faculty:
{journal_list}

#### 🌟 Top Q1 Landmark Papers:
{paper_list}
"""
        return res

    # 4. Top Authors Intent
    elif any(k in prompt_lower for k in ["author", "faculty", "h-index", "leaderboard", "researcher", "scholar"]):
        leaderboard_df = get_top_authors_leaderboard(df, top_n=5)
        
        author_rows = ""
        for idx, r in leaderboard_df.iterrows():
            rank_emoji = ["🥇", "🥈", "🥉", "4️⃣", "5️⃣"][idx]
            author_rows += f"| {rank_emoji} **{r['author']}** | {r['primary_department']} | {r['paper_count']} | {r['total_citations']:,} | {r['cpp']} | **h-{r['h_index']}** |\n"

        res = f"""### 👥 Top Faculty Researchers Leaderboard

| Faculty Member | Primary Department | Papers | Citations | CPP | h-Index |
| :--- | :--- | :---: | :---: | :---: | :---: |
{author_rows}
> 🏆 **Faculty Leader:** **{leaderboard_df.iloc[0]['author']}** leads with an estimated **h-index of h-{leaderboard_df.iloc[0]['h_index']}** and **{leaderboard_df.iloc[0]['paper_count']}** publications.
"""
        return res

    # 5. Targeted Keyword / Year / Topic Intent
    else:
        # Check if year is mentioned (e.g. 2025, 2026)
        year_match = re.search(r'\b(20\d\d)\b', prompt_lower)
        if year_match:
            yr = int(year_match.group(1))
            yr_df = df[df['year'] == yr]
            if not yr_df.empty:
                return f"### 📅 Publication Insights for Year {yr}\n\n- **Total Papers Published:** `{len(yr_df):,}`\n- **Total Citations Earned:** `{int(yr_df['citations'].sum()):,}`\n- **Q1 Publications:** `{int((yr_df['quartile'] == 'Q1').sum())}`\n- **Top Cited Paper in {yr}:** *{yr_df.sort_values('citations', ascending=False).iloc[0]['title']}* ({yr_df.sort_values('citations', ascending=False).iloc[0]['citations']} citations)"

        # Search keyword in titles, departments, or journals
        matches = df[df['title'].str.lower().str.contains(prompt_lower, na=False) | 
                     df['department'].str.lower().str.contains(prompt_lower, na=False) |
                     df['journal'].str.lower().str.contains(prompt_lower, na=False)]

        if not matches.empty:
            m_count = len(matches)
            m_cites = int(matches['citations'].sum())
            top_m = matches.sort_values('citations', ascending=False).head(3)
            
            p_list = ""
            for idx, r in top_m.iterrows():
                p_list += f"- **{r['title']}** ({r['year']}) - *{r['journal']}* | {r['citations']} citations\n"

            return f"### 🔍 Search Query Insights: \"{prompt}\"\n\nFound **{m_count}** matching publications with **{m_cites:,}** total citations.\n\n#### Top Relevant Papers:\n{p_list}"

        # Default Intelligent Summary
        kpis = calculate_top_10_kpis(df)
        return f"""### 🤖 BAMU Scopus AI Copilot Intelligence Summary

I analyzed `{total_pubs:,}` publications in the current active dataset.

- 📊 **Total Output:** `{kpis['total_output']:,}` indexed papers
- 📈 **Total Citations:** `{kpis['total_citations']:,}` (Average `{kpis['citations_per_paper']}` citations per paper)
- 🏆 **Q1 Quality Ratio:** `{kpis['q1_percentage']}%` (`{kpis['q1_count']:,}` Q1 papers)
- 🌐 **International Collab Rate:** `{kpis['international_collab_pct']}%`

*Try asking me specific questions like: "Department rankings", "Top Q1 papers", "Faculty h-index leaderboard", or "Executive dossier"!*
"""


if __name__ == "__main__":
    from mock_data import generate_mock_publications
    mock_df = pd.DataFrame(generate_mock_publications(100))
    print(query_ai_copilot(mock_df, "Executive Dossier"))
